import type { DLPPattern } from './types';

/** Credential/secret detection patterns (reuses patterns from credvault/secretless) */
export const SECRET_PATTERNS: DLPPattern[] = [
  {
    id: 'secret-anthropic',
    name: 'Anthropic API Key',
    regex: /\bsk-ant-api\d{2}-[A-Za-z0-9_-]{20,}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-openai',
    name: 'OpenAI API Key',
    regex: /\bsk-[A-Za-z0-9]{20,}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-aws-key',
    name: 'AWS Access Key',
    regex: /\b(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-github-pat',
    name: 'GitHub Personal Access Token',
    regex: /\bghp_[A-Za-z0-9]{36,}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-github-fine',
    name: 'GitHub Fine-Grained Token',
    regex: /\bgithub_pat_[A-Za-z0-9_]{22,}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-gcp',
    name: 'GCP API Key',
    regex: /\bAIza[A-Za-z0-9_-]{35}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-slack-token',
    name: 'Slack Token',
    regex: /\bxox[bporas]-[A-Za-z0-9-]{10,}\b/g,
    severity: 'high',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-stripe',
    name: 'Stripe API Key',
    regex: /\b[rs]k_(?:live|test)_[A-Za-z0-9]{20,}\b/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-private-key',
    name: 'Private Key Header',
    regex: /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g,
    severity: 'critical',
    category: 'credential',
    maskStrategy: 'full',
  },
  {
    id: 'secret-jwt',
    name: 'JSON Web Token',
    regex: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g,
    severity: 'high',
    category: 'credential',
    maskStrategy: 'partial',
  },
  {
    id: 'secret-generic-password',
    name: 'Password Assignment',
    regex: /(?:password|passwd|pwd)\s*[:=]\s*["']([^"']{8,})["']/gi,
    severity: 'high',
    category: 'credential',
    maskStrategy: 'full',
  },
];
