/**
 * Unified Review HTML Dashboard Generator.
 *
 * Generates a self-contained HTML file with:
 * - Dark theme (#0f172a bg, #1e293b cards, teal primary)
 * - Tabs: Overview (Summary and Fix first), Findings, Shadow AI, Hygiene
 * - Composite score gauge with recovery summary
 * - Phase status cards with timing
 * - Cross-tab navigation
 * - Copy buttons for remediation commands
 *
 * No external dependencies. No emojis. Monospace font.
 */

import type { ReviewReport } from '../commands/review.js';
import { assembleReviewClientScript, reviewReportCss } from './review-assets.js';

function esc(s: string | null | undefined): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

export function generateReviewHtml(report: ReviewReport): string {
  const jsonData = JSON.stringify(report).replace(/<\//g, '<\\/');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OpenA2A Security Review - ${esc(report.projectName ?? 'Project')}</title>
<style>
${reviewReportCss()}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <div>
      <div class="header-title">OpenA2A Security Review</div>
      <div class="header-subtitle">Security review of <strong style="color:var(--text)">${esc(report.projectName ?? report.directory)}</strong> -- composite score from 6 automated checks. Higher is better.</div>
    </div>
    <div class="header-meta">${esc(report.timestamp)}</div>
  </div>
  <nav class="nav" id="main-nav">
    <button class="nav-tab active" data-page="overview">Overview</button>
    <button class="nav-tab" data-page="findings">Findings${report.reportFindings ? ` (${report.reportFindings.length})` : ''}</button>
    <button class="nav-tab" data-page="shadowai">Shadow AI</button>
    <button class="nav-tab" data-page="hygiene">Hygiene</button>
  </nav>
  <div class="page active" id="page-overview"></div>
  <div class="page" id="page-findings"></div>
  <div class="page" id="page-shadowai"></div>
  <div class="page" id="page-hygiene"></div>
  <div class="footer">Generated by <a href="https://opena2a.org" target="_blank" rel="noopener">OpenA2A</a> -- Open Agent-to-Agent Security Platform</div>
</div>
<script id="report-data" type="application/json">${jsonData}</script>
<script>
${assembleReviewClientScript()}
</script>
</body>
</html>`;
}
