/**
 * Package narrative — rich-context payload that powers the `check`
 * skill+mcp v1 view in the OpenA2A CLI fleet (HMA, opena2a-cli, ai-trust).
 *
 * Brief: opena2a-org/briefs/check-rich-context-skills-mcp-v1.md (§4)
 *
 * Wire shape mirrors the registry's `package_narratives` row (see
 * opena2a-registry/internal/domain/package_narrative.go and migration 223).
 * v1 covers `skill` and `mcp` artifact types only; npm/PyPI/A2A artifacts
 * skip the rich-context view and fall back to the existing 0.18.3 / M3
 * block plus a one-line "rich-context coming in v2" footer.
 *
 * Cache TTL is enforced by the registry (30 days OR latestVersion change).
 * Consumers receive a fresh row or a 404; staleness is not surfaced in v1.
 */

/**
 * Top-level narrative shape returned by GET /api/v1/trust/narrative
 * and rendered by `renderCheckRichBlock` (cli-ui 0.4.0, session 3).
 *
 * Exactly one of `skill` or `mcp` is set, matching the SQL CHECK
 * constraint in migration 223.
 */
export interface PackageNarrative {
  /** Bumps when the wire schema breaks. v1 = 1. */
  schemaVersion: 1;
  /** ISO timestamp the registry stamped at INSERT/UPSERT time. */
  generatedAt: string;
  /**
   * Provenance metadata so consumers can trace a rendered narrative
   * back to the scan run that produced it.
   */
  generatedFrom: {
    artifactType: ArtifactType;
    artifactVersion: string;
    scanRunId: string;
  };
  /**
   * Plain-language summary, generated by NanoMind v3 at scan time.
   * 1 paragraph, 2-4 sentences, no marketing language. May be empty
   * when comprehension data is not yet available (model failure +
   * graceful-degrade).
   */
  summary: string;
  /**
   * Hardcoded-secrets findings, surfaced as a structured block. Always
   * populated (empty `detected` array is the "clean" state) so the
   * renderer can emit the secrets section deterministically.
   */
  hardcodedSecrets: HardcodedSecretsBlock;
  /** Skill-specific narrative. Mutually exclusive with `mcp`. */
  skill?: SkillNarrative;
  /** MCP-specific narrative. Mutually exclusive with `skill`. */
  mcp?: McpNarrative;
  /**
   * Deterministic verdict reasoning produced by the rule engine.
   * Rendered verbatim under "Why VERIFIED/LISTED/BLOCKED".
   */
  verdictReasoning: VerdictReasoningStatement[];
  /**
   * Action gradient produced by the rule engine. Renderer treats
   * `primary` as the headline action and `secondary` entries as
   * follow-ups.
   */
  nextSteps: NextStep[];
}

/** v1 supported artifact types. */
export type ArtifactType = "skill" | "mcp";

/**
 * Hardcoded-secrets block. Three render states emerge from the
 * combination of `scanCovered` and `detected.length`:
 *   - !scanCovered                 → "Not yet analyzed."
 *   - scanCovered && empty         → "None detected on the latest version."
 *   - scanCovered && non-empty     → severity-grouped credential list.
 */
export interface HardcodedSecretsBlock {
  detected: HardcodedSecret[];
  /** false when the package has not been scanned (LISTED UNSCANNED tier). */
  scanCovered: boolean;
}

/**
 * One hardcoded-secret entry. The credential value is masked at
 * extraction time — the registry never stores the full secret.
 */
export interface HardcodedSecret {
  /**
   * Credential-type identifier. Drives the rotation-guidance lookup
   * in `secret-rotation.ts`. Known types: `anthropic_api_key`,
   * `openai_api_key`, `aws_access_key`, `github_pat`,
   * `slack_bot_token`, `gcp_service_account_key`, `private_key`,
   * `database_url`, `generic_bearer`, `unknown`. Unknown types fall
   * through to the generic rotation-report path.
   */
  type: string;
  /** Human-readable label rendered in the secrets block header. */
  typeLabel: string;
  /** file:line locator. `line` is optional when the scanner cannot anchor. */
  file: string;
  line?: number;
  /**
   * Masked credential. Recognizable prefix (`sk-ant-api03-`, `AKIA`,
   * `ghp_`, etc.) followed by asterisks. Unknown-type credentials
   * show their first 8 characters.
   */
  maskedValue: string;
  /** Number of leading characters preserved. */
  shownChars: number;
  /** Total characters in the original credential. */
  totalChars: number;
  /**
   * True when the file containing this credential ships in the
   * package tarball / installable artifact (vs a local-only fixture).
   * Drives the "key is already public on the registry" rotation note.
   */
  shipsInArtifact: boolean;
  /**
   * Per-secret severity. Differs by credential type and ship state:
   * a hardcoded private_key in the tarball is `critical` regardless;
   * a generic_bearer in a local-only fixture may be `low`.
   */
  severity: SecretSeverity;
  /** Service-specific rotation URL, populated by the rule engine. */
  rotationUrl?: string;
  /** Service-specific rotation command. May be the only safe path. */
  rotationCommand?: string;
}

export type SecretSeverity = "critical" | "high" | "medium" | "low";

/**
 * Skill-specific narrative. Activation phrases, declared-vs-observed
 * permission delta, observed external services, and the misuse-narrative
 * paragraph all live here.
 */
export interface SkillNarrative {
  skillName: string;
  /** Activation phrases as declared in SKILL.md frontmatter. */
  activationPhrases: string[];
  /**
   * 1-2 sentence behavior description, generated by NanoMind v3 at
   * scan time and cached. May be empty when comprehension data is
   * not yet available.
   */
  behaviorDescription: string;
  /** Declared-vs-observed permission delta. */
  permissions: PermissionStatus[];
  /** External services the skill talks to, AST-extracted from source. */
  externalServices: string[];
  /** Persistence side effects ("none", "filesystem", "database", etc.). */
  persistence: string;
  /** Tool-call counts observed during semantic analysis. */
  toolCallsObserved: ToolCallCount[];
  /**
   * Misuse-narrative paragraph, generated by NanoMind v3, anchored on
   * the declared/observed delta — not generic FUD. Empty string when
   * comprehension data is not yet available.
   */
  misuseNarrative: string;
  /**
   * Static threat-model questions for the skill artifact type.
   * Curated by [CHIEF-CSR]; rendered verbatim. Lives here (not in
   * cli-ui) so the registry stores everything the renderer needs.
   */
  threatModelQuestions: string[];
}

/**
 * MCP-specific narrative. Tool list, scope blocks, and observed
 * side effects.
 */
export interface McpNarrative {
  mcpName: string;
  /** Tool signatures exposed by the MCP server. */
  tools: McpTool[];
  /**
   * Path scope description. Free-form so the renderer can surface
   * nuance (e.g. "any path agent passes" vs "config-allowlisted").
   */
  pathScope: string;
  /** Network surface ("none", domain list, etc.). */
  network: string;
  /** Persistence side effects. */
  persistence: string;
  /** Authentication model ("none", "bearer token", etc.). */
  auth: string;
  /** Observed process-level side effects (spawn, fs writes, etc.). */
  sideEffects: string[];
  /** Static threat-model questions for the MCP artifact type. */
  threatModelQuestions: string[];
}

export interface McpTool {
  name: string;
  /** Tool signature, e.g. `read_file(path)`. */
  signature: string;
  /** Single-line description from MCP tool registration. */
  description: string;
  /** True when the tool mutates state (write/move/delete). */
  destructive: boolean;
}

/**
 * Declared-vs-observed permission entry. The renderer uses `status`
 * and `note` to render markers like `[used]`, `[unused]`, `[—]`.
 */
export interface PermissionStatus {
  /** Permission name, e.g. "Read", "Bash", "WebFetch". */
  name: string;
  declared: boolean;
  used: boolean;
  /**
   * `used` = declared and used as expected.
   * `unused` = declared but not invoked in any reference flow.
   * `undeclared` = used but not declared (declared=false, used=true).
   */
  status: PermissionDeltaStatus;
  /** Optional context for the renderer. */
  note?: string;
}

export type PermissionDeltaStatus = "used" | "unused" | "undeclared";

export interface ToolCallCount {
  tool: string;
  count: number;
}

/**
 * Single statement under "Why VERIFIED/LISTED/BLOCKED". Rule engine
 * emits these in render order; the renderer prefixes each with the
 * appropriate marker (`[ok]`, `[gap]`, `CRITICAL`, ...).
 */
export interface VerdictReasoningStatement {
  /**
   * `positive` supports the trust tier.
   * `gap` blocks the next-higher tier.
   * `critical` drives BLOCKED — at least one is required for BLOCKED.
   */
  kind: "positive" | "gap" | "critical";
  text: string;
}

/**
 * One entry in the action gradient. `primary` is the headline action;
 * the renderer treats the first `primary` as the top line. `secondary`
 * entries follow.
 */
export interface NextStep {
  weight: "primary" | "secondary";
  /** Action label, e.g. "Install confidently", "Rotate the leaked key first". */
  label: string;
  /** Shell command the user should run, when applicable. */
  command?: string;
  /** Web URL (rotation page, alternative-package suggestion, etc.). */
  url?: string;
}
